### ISSUE TITLE
Enable key repeat in Love

### ISSUE THREAD

**Issue by rm-code** [airstruck/luigi#15]
It would be nice if Luigi would allow certain actions to be performed as long as a button is pressed (e.g.: Deleting characters while backspace is pressed, or moving the cursor when the arrow keys are pressed).

All in all it is looking pretty nice already :blush:  I would love to implement it in some of my projects asap :+1:

**Comment by airstruck** [comment]
Love turns key repeat off by default, but you can turn it on with `love.keyboard.setKeyRepeat(true)`. In the SDL backend key repeat is already on by default. I'm not sure if I want to override the default behavior for Love, what do you think?

**Comment by rm-code** [comment]
Oh I totally forgot about `love.keyboard.setKeyRepeat`. In this case I don't think you should change the default behavior.
