### ISSUE TITLE
Finalize 0.1.0 release candidate

### ISSUE THREAD

**Issue by airstruck** [airstruck/luigi#31]
Need to address #2 and #3, update API docs, and write some supporting documentation (examples/tutorials) for 0.1.0 RC.

What else needs to get done before this project is formally announced?

**Comment by rm-code** [comment]
Documentation?

**Comment by airstruck** [comment]
Yeah :(

**Comment by airstruck** [comment]
Going to push public release candidate back to 0.2.0 and skip 0.1.0 release.
