### ISSUE TITLE
Can't enter a 'z' on the input box

### ISSUE THREAD

**Issue by ghost** [airstruck/luigi#37]
I can't enter the letter 'z' on the input box. When doing so, it presses a button instead and the input box loses focus.

Happens with both love2d and luajit+SDL.

**Comment by airstruck** [comment]
Thanks for catching that. I'm getting slightly different behavior; I can enter a z in the box, but the keypress also triggers the button with the shortcut assigned to z without stealing focus from the text box. What version of Love or SDL did you get that behavior under?

**Comment by ghost** [comment]
Thanks for the quick fixes! To answer your question, it was happening with all versions (LOVE 9, 10 and luajit), with both SDL 2.0.2 and 2.0.4. One factor may be that I'm using Linux.

**Comment by airstruck** [comment]
That's really strange, I'm testing under 9, 10, and 2.0.4 on Debian 8. Anyway it should be somewhat fixed for now, I opened a thread on Love forums to try to explore ways to improve it, but have just been getting the usual runaround so far: https://love2d.org/forums/viewtopic.php?f=4&t=81729

**Comment by ghost** [comment]
Yes. To clarify, it no longer happens since the fix. I was just talking about what happened before the fix. The text widget lost focus, which went to the upper button. Pressing tab again switched to the second button.

**Comment by airstruck** [comment]
Yeah, that's what I thought you meant. Before the fix, the behavior I got was the button was triggered, but didn't steal focus. No idea why we were getting different behavior, but it should be resolved now anyway.
